modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/cofh/feedback"

[[mods]]
    modId="thermal_dynamics"
    version="0.1.0a"
    displayName="Thermal Dynamics"
    displayURL="https://teamcofh.com/"
    logoFile="logo.png"
    credits="Team CoFH"
    authors="King Lemming"
    description='''
Thermal Dynamics!
'''
[[dependencies.thermal_dynamics]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.thermal_dynamics]]
    modId="forge"
    mandatory=true
    versionRange="[28.1.90,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.thermal_dynamics]]
    modId="cofh_core"
    mandatory=true
    versionRange="[0.3,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.thermal_dynamics]]
    modId="thermal"
    mandatory=true
    versionRange="[0.1.0a]"
    ordering="AFTER"
    side="BOTH"