modLoader = "javafml"
loaderVersion = "[31,)"
issueTrackerURL = "https://github.com/cofh/feedback"

[[mods]]
modId = "thermal"
version = "${file.jarVersion}"
displayName = "Thermal Series"
updateJSONURL = "https://raw.github.com/cofh/version/master/thermal/update.json"
displayURL = "https://teamcofh.com/"
logoFile = "logo.png"
credits = "Team CoFH"
authors = "King Lemming"
description = '''
Parent mod for all Thermal modules. The Foundation of a Thermally Expanding World!
'''
[[dependencies.thermal]]
modId = "minecraft"
mandatory = true
versionRange = "[1.15.2]"
ordering = "AFTER"
side = "BOTH"

[[dependencies.thermal]]
modId = "forge"
mandatory = true
versionRange = "[31.2.30,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.thermal]]
modId = "cofh_core"
mandatory = true
versionRange = "[0.5,)"
ordering = "AFTER"
side = "BOTH"