modLoader = "javafml"
loaderVersion = "[31,)"
issueTrackerURL = "https://github.com/cofh/feedback"

[[mods]]
modId = "thermal_expansion"
version = "${file.jarVersion}"
displayName = "Thermal Expansion"
displayURL = "https://teamcofh.com/"
logoFile = "logo.png"
credits = "Team CoFH"
authors = "King Lemming"
description = '''
Expanding Minecraft Thermally! A server-friendly and content-rich blend of magic and technology!

Contains the "factory" of the Thermal Series - Dynamos and Machines to both produce and process.
'''
[[dependencies.thermal_expansion]]
modId = "minecraft"
mandatory = true
versionRange = "[1.15.2]"
ordering = "AFTER"
side = "BOTH"

[[dependencies.thermal_expansion]]
modId = "forge"
mandatory = true
versionRange = "[31.1.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.thermal_expansion]]
modId = "cofh_core"
mandatory = true
versionRange = "[0.7,0.8]"
ordering = "AFTER"
side = "BOTH"

[[dependencies.thermal_expansion]]
modId = "thermal"
mandatory = true
versionRange = "[0.3,0.4]"
ordering = "AFTER"
side = "BOTH"