modLoader = "javafml"
loaderVersion = "[31,)"
issueTrackerURL = "https://github.com/cofh/feedback"

[[mods]]
modId = "thermal_expansion"
version = "${file.jarVersion}"
displayName = "Thermal Expansion"
displayURL = "https://teamcofh.com/"
logoFile = "logo.png"
credits = "Team CoFH"
authors = "King Lemming"
description = '''
Thermal Expansion!
'''
[[dependencies.thermal_expansion]]
modId = "minecraft"
mandatory = true
versionRange = "[1.15.2]"
ordering = "AFTER"
side = "BOTH"

[[dependencies.thermal_expansion]]
modId = "forge"
mandatory = true
versionRange = "[31.1.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.thermal_expansion]]
modId = "cofh_core"
mandatory = true
versionRange = "[0.5,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.thermal_expansion]]
modId = "thermal"
mandatory = true
versionRange = "[0.1,)"
ordering = "AFTER"
side = "BOTH"