modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/cofh/feedback"

[[mods]]
    modId="cofh_potions"
    version="0.0.1a"
    displayName="CoFH Potions"
    credits="Team CoFH"
    authors="King Lemming"
    description='''
CoFH Potions!
'''
[[dependencies.cofh_potions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.cofh_potions]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.cofh_potions]]
    modId="cofh_core"
    mandatory=true
    versionRange="[0.2,)"
    ordering="AFTER"
    side="BOTH"