modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/cofh/feedback"

[[mods]]
    modId="cofh_test"
    version="0.0.1a"
    displayName="CoFH Test"
    credits="Team CoFH"
    authors="King Lemming"
    description='''
Testing ground for CoFH features. Or, King Lemming's Playground of Coding Horrors.
'''
[[dependencies.cofh_test]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"

[[dependencies.cofh_test]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.cofh_test]]
    modId="cofh_core"
    mandatory=true
    versionRange="[0.0,)"
    ordering="NONE"
    side="BOTH"