modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/cofh/feedback"

[[mods]]
    modId="thermal_essentials"
    version="0.1.0a"
    displayName="Thermal Essentials"
    displayURL="https://teamcofh.com/"
    logoFile="logo.png"
    credits="Team CoFH"
    authors="King Lemming"
    description='''
Thermal Essentials!
'''
[[dependencies.thermal_essentials]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.thermal_essentials]]
    modId="forge"
    mandatory=true
    versionRange="[31.1.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.thermal_essentials]]
    modId="cofh_core"
    mandatory=true
    versionRange="[0.3,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.thermal_essentials]]
    modId="thermal"
    mandatory=true
    versionRange="[0.1.0a]"
    ordering="AFTER"
    side="BOTH"