modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/cofh/feedback"

[[mods]]
    modId="thermal_locomotion"
    version="0.1.0a"
    displayName="Thermal Locomotion"
    displayURL="https://teamcofh.com/"
    logoFile="logo.png"
    credits="Team CoFH"
    authors="King Lemming"
    description='''
Thermal Locomotion!
'''
[[dependencies.thermal_locomotion]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.thermal_locomotion]]
    modId="forge"
    mandatory=true
    versionRange="[31.2.30,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.thermal_locomotion]]
    modId="cofh_core"
    mandatory=true
    versionRange="[0.4,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.thermal_locomotion]]
    modId="thermal"
    mandatory=true
    versionRange="[0.1.0a]"
    ordering="AFTER"
    side="BOTH"