modLoader="javafml"
loaderVersion="[26,)"
issueTrackerURL="http://my.issue.tracker/"
[[mods]]
modId="cofh_core"
version="${file.jarVersion}"
displayName="CoFH Core"
#updateJSONURL="http://myurl.me/"
displayURL="http://example.com/"
logoFile="logo.png"
credits="Team CoFH"
authors="King Lemming"
description='''

CoFH Core!

'''
[[dependencies.cofh_core]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.3]"
    ordering="NONE"
    side="BOTH"

[[dependencies.cofh_core]]
    modId="forge"
    mandatory=true
    versionRange="[27,)"
    ordering="NONE"
    side="BOTH"