modLoader="javafml"
loaderVersion="[26,)"
issueTrackerURL="http://my.issue.tracker/"

[[mods]]
    modId="cofh_core"
    version="${file.jarVersion}"
    displayName="CoFH Core"
    #updateJSONURL="http://myurl.me/"
    #displayURL="http://example.com/"
    logoFile="logo.png"
    credits="Team CoFH"
    authors="King Lemming, covers1624, skyboy"
    description='''
Core Library required for the functionality of all CoFH mods.

Also contains a number of optional gameplay tweaks for convenience.
'''
[[dependencies.cofh_core]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"

[[dependencies.cofh_core]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"