modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/cofh/feedback"

[[mods]]
    modId="ensorcellation"
    version="0.4.1b"
    displayName="Ensorcellation"
    updateJSONURL="https://raw.github.com/cofh/version/master/ensorcellation/update.json"
    displayURL="https://teamcofh.com/"
    logoFile="logo.png"
    credits="Team CoFH"
    authors="King Lemming"
    description='''
Adds a multitude of highly configurable Enchantments!

Also improves functionality and flexibility of some vanilla Minecraft Enchantments.

Suitable for both lightly and heavily modded worlds.
'''
[[dependencies.ensorcellation]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.ensorcellation]]
    modId="forge"
    mandatory=true
    versionRange="[31.1.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.ensorcellation]]
    modId="cofh_core"
    mandatory=true
    versionRange="[0.4,)"
    ordering="AFTER"
    side="BOTH"