modLoader="javafml"
loaderVersion="[26,)"
issueTrackerURL="http://my.issue.tracker/"

[[mods]]
    modId="cofh_world"
    version="${file.jarVersion}"
    displayName="CoFH World"
    #updateJSONURL="http://myurl.me/"
    #displayURL="http://example.com/"
    logoFile="logo.png"
    credits="Team CoFH"
    authors="King Lemming"
    description='''

CoFH World!

'''
[[dependencies.cofh_world]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"

[[dependencies.cofh_world]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"