modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/cofh/feedback"

[[mods]]
    modId="archers_paradox"
    version="0.3.0b"
    displayName="Archer's Paradox"
    updateJSONURL="https://raw.github.com/cofh/version/master/archers_paradox/update.json"
    displayURL="https://teamcofh.com/"
    logoFile="logo.png"
    credits="Team CoFH"
    authors="King Lemming"
    description='''
Adds many new varieties of arrows.

Suitable for both lightly and heavily modded worlds.
'''
[[dependencies.archers_paradox]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.archers_paradox]]
    modId="forge"
    mandatory=true
    versionRange="[28.1.90,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.archers_paradox]]
    modId="cofh_core"
    mandatory=true
    versionRange="[0.3,)"
    ordering="AFTER"
    side="BOTH"