modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/cofh/feedback"

[[mods]]
    modId="cofh_archery"
    version="0.0.1a"
    displayName="CoFH Archery"
    credits="Team CoFH"
    authors="King Lemming, Drullkus"
    description='''
CoFH Archery!
'''
[[dependencies.cofh_archery]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"

[[dependencies.cofh_archery]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.cofh_archery]]
    modId="cofh_core"
    mandatory=true
    versionRange="[0.2,)"
    ordering="NONE"
    side="BOTH"